; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=PAKU Manga PDF Reader
AppVersion=1.0
DefaultDirName={pf}\PAKU
DefaultGroupName=PAKU
OutputDir=.
OutputBaseFilename=PAKU-Setup
Compression=lzma
SolidCompression=yes
; SetupIconFile=assets\images\logo.ico

[Files]
Source: "dist\\*"; DestDir: "{app}"; Flags: recursesubdirs

[Icons]
Name: "{group}\PAKU"; Filename: "{app}\Paku.exe"
Name: "{userdesktop}\PAKU"; Filename: "{app}\Paku.exe"; Tasks: desktopicon

[Tasks]
Name: desktopicon; Description: "Créer un raccourci sur le Bureau"; GroupDescription: "Icônes supplémentaires:"

[Run]
Filename: "{app}\Paku.exe"; Description: "Lancer PAKU Manga PDF Reader"; Flags: nowait postinstall skipifsilent